### ISSUE TITLE
The titles contain a spelling mistake!

### ISSUE THREAD

**Issue by DavidHaslam** [tyndale/STEPBible-Data#1]
It should be "Tyndale Brief lexicon of **Extended** Strongs for Hebrew"

@DavidIB

**Comment by DavidHaslam** [comment]
Likewise for "Tyndale Brief lexicon of **Extended** Strongs for Greek"

**Comment by DavidHaslam** [comment]
Likewise in the mentions of both in **README.md**

**Comment by DavidIB** [comment]
Thanks!

At 14:53 01/05/2018, David Frank Haslam wrote:

**Comment by DavidHaslam** [comment]
It's usual to only close an issue after the commit that fixes it.

The titles in the folder names are unchanged.
https://www.dropbox.com/s/n7uylgjmd5qdhcc/Screenshot%202018-05-02%2011.21.18.png?dl=0

**Comment by DavidIB** [comment]
Ah - I see what you mean!

At 11:23 02/05/2018, David Frank Haslam wrote:

**Comment by DavidIB** [comment]
I thought I did fix it. Did I forget to Commit?

At 11:23 02/05/2018, David Frank Haslam wrote:

**Comment by DavidIB** [comment]
Do you, by any chance, know how to rename files 
that are larger than can be opened in Raw view?
With small files (eg the README) you can open and 
edit it, and then you have the option to rename it.
With files that are too large to edit there 
doesn't appear to be any Rename facility.
I've always had to deal with this in the past by 
deleting and recreating the files, but of course 
this deletes the file history. Surely there must be a better way?
Using command line, I think it is only possible 
to rename a file that you have cloned. You could 
of course upload it after renaming it, but that's 
the same thing as deleting and recreating.

Any ideas?  (as you can see, I don't know Github or git very well)

David IB


At 11:23 02/05/2018, David Frank Haslam wrote:

**Comment by DavidHaslam** [comment]
Sorry, that's not something I've had to tackle before with GitHub. I'm not an expert Git user.
I sometime use the GitHub Desktop client for Windows, but that's only going to be like deleting and uploading again.

Maybe @chrisburrell might be able to advise...

**Comment by DavidHaslam** [comment]
This might help.
[Renaming a file using the command line](https://help.github.com/articles/renaming-a-file-using-the-command-line/)

**Comment by DavidIB** [comment]
Thanks for your help, David

**Comment by DavidIB** [comment]
This seems to tell you how to clone and rename - 
but that leaves the original the same.
Ah well - I'll do it the old way. Scrap and recreate.
I suppose they don't bother with rename because 
long files don't keep a diff record, so you don't 
lose much when you simply delete and recreate.
Thanks for looking

David IB

At 11:23 03/05/2018, David Frank Haslam wrote:

**Comment by jonathanrobie** [comment]
Did you do a 'git push'?

I'm wondering if you committed to your local repository (git commit) without pushing it to github (git push).
