### ISSUE TITLE
Missing words in Matthew

### ISSUE THREAD

**Issue by eliranwong** [tyndale/STEPBible-Data#13]
Dear David,

  I am checking TANTT with NA27.  I observed that there are still missing words in TANTT.

For example, in Matthew,

Mat 1:22 "ὑπὸ κυρίου διὰ" instead of "ὑπὸ διὰ"
Mat 12:4 "ὃ οὐκ" instead of "οὐκ"
Mat 14:34 "ἐπὶ τὴν" instead of "τὴν"
Mat 15:30 "κυλλούς, κωφούς⸃, καὶ" instead of "καὶ"
...

**Comment by DavidIB** [comment]
Corrected

**Comment by DavidIB** [comment]
Thanks again for your work. 

You have helped me identify yet another error in my export code

 

David IB
