### ISSUE TITLE
Few more missing and extra words

### ISSUE THREAD

**Issue by eliranwong** [tyndale/STEPBible-Data#15]
Dear David,

There are missing words in:
Mark 16:20, "ἐπακολουθούντων σημείων" instead of "ἐπακολουθούντων"
Luke 19:38, "ὁ βασιλεὺς" instead of "βασιλεὺς"
John 10:29, "ὃ δέδωκέν" instead of "δέδωκέν"
John 12:18, "τοῦτο αὐτὸν" instead of "τοῦτο"
John 13:12, "καὶ ἔλαβεν" instead of "ἔλαβεν"
Acts 19:6, "τὰς χεῖρας" instead of "χεῖρας"
Titus 1:10, "καὶ ἀνυπότακτοι" of "ἀνυπότακτοι"
Rev 6:15, "οἱ ἰσχυροὶ" instead "ἰσχυροὶ"

There are extra words in:
Mat 19:24, "θεοῦ" instead of "θεοῦ κυρίου"
Luke 21:34, "καὶ" instead of "καὶ ἐφ᾽ ὑμᾶς"
John 6:58, "πατέρες" instead of "πατέρες ὑμῶν τὸ μάννα"
John 8:38, "τοῦ" instead of "τοῦ τῷ"
John 14:5, "πῶς" instead of "πῶς οἴδαμεν"
John 14:7, "μου" instead of "μου ἂν ᾔδειτε"
Acts 16:12, "πρώτης" instead of "πρώτη πρώτης"
Rom 13:11, "ὑμᾶς" instead of "ὑμᾶς ἡμᾶς"
1Co 3:12, "χρυσόν ἄργυρον" instead of "χρυσόν χρυσίον ἄργυρον ἀργύριον"
1Peter 3:18, "ἔπαθεν" instead of "ἔπαθεν ἀπέθανεν"
Rev 20:11, "καθήμενον" instead of "καθήμενον αὐτοῦ"

Others, in:
Luke 5:36, NA27 = "μή γε"; TANTT = "μήγε"
Luke 5:37, NA27 = "μή γε"; TANTT = "μήγε"
Luke 10:6, NA27 = "μή γε"; TANTT = "μήγε"
Luke 13:9, NA27 = "μή γε"; TANTT = "μήγε"
Luke 14:32, NA27 = "μή γε"; TANTT = "μήγε"
Rom 11:21, NA27 = "μή πως"; TANTT = "μήπως"
Luke 2:48, NA27 = "κἀγὼ"; TANTT = "καὶ ἐγὼ"

**Comment by DavidIB** [comment]
Fixed - thanks again for your help
