### ISSUE TITLE
TANTT - 2 missing words & 1 extra word in the latest file

### ISSUE THREAD

**Issue by eliranwong** [tyndale/STEPBible-Data#17]
Dear David,

In the latest file, there are

2 Missing words:
In Matthew 15: 1 "καὶ γραμματεῖς λέγοντες" instead of "καὶ λέγοντες"
In John 12:18, "καὶ ὑπήντησεν" instead of "ὑπήντησεν"

1 Extra Word:
In Rom 11:21, "μή πως" instead of "μήπως μή πως"

Thanks for your great work.

**Comment by DavidIB** [comment]
Fixed. THanks again.
