### ISSUE TITLE
TANTT - line 13161, 13162

### ISSUE THREAD

**Issue by eliranwong** [tyndale/STEPBible-Data#19]
Dear David,

I would like to suggest a correction.

Current data:
41_Mat.017.026	H	αρα	ἄρα	G0686	CONJ	ἄρα	therefore			
41_Mat.017.026	H	γε	γε	G1065	PRT	γέ	indeed		

Corrections:
41_Mat.017.026	IMNH	αρα	ἄρα	G0686	CONJ	ἄρα	therefore			
41_Mat.017.026	IMNH	γε	γε	G1065	PRT	γέ	indeed		

Blessings,
Eliran

**Comment by DavidIB** [comment]
Dear Eliran

 

Thank you so much for pointing this out. I’m not sure why I didn’t correct it the first time. 

This made me look again at my code for checking, and found there was a problem. When I corrected it, I found an additional error – the comma at the end of Jude 22 was missing. This is also now corrected – thanks to you. 

 

All the best 

 

David IB

**Comment by eliranwong** [comment]
Thanks for the fix, David.
