### ISSUE TITLE
TBESH - double entries of H3756, H3757 is missing

### ISSUE THREAD

**Issue by eliranwong** [tyndale/STEPBible-Data#2]
I think there is a typo.  One of H3756 is H3757

**Comment by DavidIB** [comment]
H3757 is used for the gentilic ‘Carmite’ and H3756 is used for the personal name ‘Carmi’

I can only find one instance of H3757, at Num.026.006-06, and it appears to be correct. 

Is that the one you were referring to? 

 

David IB

**Comment by eliranwong** [comment]
I should have had given more details.

In the file, "TBESH - Tyndale Brief lexicon of Extended Strongs for Hebrew - TyndaleHouse.com STEPBible.org CC BY-NC-ND.txt", at this repo,

line 4035 - "H3756	כַּרְמִי	N:N-M-P	Carmi	..."
line 4036 - "H3756	כַּרְמִי	N:N-M-P	Carmite	..."

There are two entries on H3756.
However, there is no entry for H3757.

It appears to me that there may be a typo in line 4036.
I think the entry in 4036 is H3757, rather than H3756.

**Comment by DavidIB** [comment]
Thanks!

I’ve corrected the source data it so it will correct when the repository is updated

 

David IB
