### ISSUE TITLE
Morphology data in TANTT

### ISSUE THREAD

**Issue by eliranwong** [tyndale/STEPBible-Data#20]
Dear David,

In TANTT,

What is "V1" in "SW=ἑαυτοὺς=G1438=F-3APM.V1"?
What is "-K" in "D-DPM-K" & "F-2ASM-K"?
"A-ANP-C" is found once in TANTT, I guess it may be "A-APN-C" instead.  Or does it mean something else?

Blessings,
Eliran

**Comment by DavidIB** [comment]
"V1"  may be a left-over on some lengthy checking we did with ἑαυτ*
-K is "Correlative". It only occ 22x in the TANTT though WHNU morph records it about 150x. It is on my ToDo list to compare these.
Thanks for the correction re A-ANP-C
