### ISSUE TITLE
Versification data

### ISSUE THREAD

**Issue by curiousdannii** [tyndale/STEPBible-Data#21]
> If you see data that you have need of which isn’t yet available, please contact us and perhaps you can become part of the checking process.

In that spirit, do you have any data on versification systems? There is limited data publicly available, and it's never very comprehensive. And often when people do have data, they only have the number of verses per chapter in each system, rather than explaining what's actually the cause of the differences (chapter breaks in different places, joined or split verses, etc.)

[I've been collecting versification resources](https://github.com/curiousdannii/reversify/wiki/Versification-systems-resources) as I come across from them, but still haven't found anything that's ideal, and no one seems keen to put forward their data as a definitive resource. (I've asked [openscriptures.org](https://github.com/openscriptures/BibleOrgSys/issues/20) too. I should ask Accordance and Logos, they must have a lot of data, and it doesn't seem like something that would hurt their profitability if they published it publicly.)

So yeah, an easy request, but not so easy to fulfil. :)

**Comment by robertrouse** [comment]
Have you looked into https://www.digitalbibleplatform.com/?

**Comment by curiousdannii** [comment]
@robertrouse No, I hadn't seen that. Thanks for the link. I just took a look, and it's not very clear how you'd get versification data out of it. And in any case, an API is different from a resource which can be freely downloaded and shared under a FLOSS or CC license.

**Comment by eliranwong** [comment]
Hi Dannii,

I am not sure what kind of data you need.

here is detailed versification difference between BHS and KJV:
https://github.com/eliranwong/OpenHebrewBible

between KJV and NA28:
https://github.com/eliranwong/OpenGNT/tree/master/OpenGNT-concordance

between LXX and KJV:
https://github.com/eliranwong/LXX-Rahlfs-1935/tree/master/08_versification/resources_on_mapping

Blessings,
Eliran Wong
https://marvel.bible
https://BibleBento.com
https://OpenGNT.com

The content of this email is confidential and intended for the recipient specified in message only. If you have received this email in error please notify the system manager. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by curiousdannii** [comment]
Hi @eliranwong, thanks those look like some good resources.

The goals I'd have for a definitive versification resource:

 - Comprehensive. If you include the Vulgate and LXX I imagine there could be half a dozen or more versifications for source texts, plus the dozens for translations.
 - Machine and human readable
 - Descriptive: not just a mapping of verse numbers, but a description of the cause (chapter breaks, verse joins/splits, Psalm headings, transposed verses, etc)
 - Possibly hierarchical? Versification systems can probably be organised in a hierarchical manner. For example, the NAB and NJPS (and others) represent a family of versifications distinct from the more common KJV family. It would be both more efficient in terms of file size, as well as more clear to users, if the data could be modelled with a hierarchy, one system being based on another and then adding its unique differences. As long as it remains machine readable, it would be possible to automatically produce flattened versions.

You can see one that I have started on here: https://github.com/curiousdannii/reversify/blob/master/src/transformations.data
I've been thinking about redoing it in YAML, which would be a bit more verbose, but would be more easy for others to consume. And I've also been thinking that changing to a hierarchical model would be beneficial, as I explained above.

**Comment by jonathanrobie** [comment]
We have this data for Paratext.  The current format is not ideal, but I can
look into putting this on GitHub, I have to get permission.

Jonathan

**Comment by DavidIB** [comment]
I've now published what is, I think, full versification data as TVTMS. 
Is there anything missing?

**Comment by curiousdannii** [comment]
Excellent, thank you!

I've been focusing mostly on English translations, so it's great to get solid data on the source texts.

**Comment by DavidIB** [comment]
Danni - I expect you realise, but just in case: the data can be used to reversify any Bible in any language, including the English ones.
