### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by jcuenod** [tyndale/STEPBible-Data#22]
https://github.com/tyndale/STEPBible-Data/blob/a18dc6acab74cd923f6f4da10b393d556725a592/TSVAN%20-%20Tyndale%20Standard%20Versification%20Alignment%20%26%20Notes%20for%20Eng%2BHeb%2BLat%2BGrk%2BOthers%20-%20TyndaleHouse.com%20STEPBible.org%20CC%20BY-NC.txt#L91

Should be `undivided` rather than `undived`.

**Comment by DavidIB** [comment]
Thanks! Fixed in next update
