### ISSUE TITLE
TBESG - verse reference formatting

### ISSUE THREAD

**Issue by eliranwong** [tyndale/STEPBible-Data#24]
Dear David,

  Thanks for adding tagging on verse references.

  I found a minor formatting issue like this:

<a href="javascript:void(0)" title="<ref="Tob.7.2; 9.6">Tob.7:2 9:6</ref>">

Blessings,
Eliran

**Comment by DavidIB** [comment]
Looks right to me. That is, "Tob.7.2; 9.6"  is correct, and "Tob.7:2 9:6" is what the electronic source has, and hasn’t been changed. I don’t like it either.

**Comment by DavidIB** [comment]
Ah - I see - the <a href is open!

**Comment by DavidIB** [comment]
Changed eg
<a href="javascript:void(0)" title="<ref="Gen.4.2-10">Gen.4:2-10</ref>): <ref="Heb.11.4; 12.24">Heb.11:4, 12:24</ref>">Refs</a>
TO: 
<a href="javascript:void(0)" title="<ref='Gen.4.2-10'>Gen.4:2-10</ref>): <ref='Heb.11.4; 12.24'>Heb.11:4, 12:24</ref>">Refs</a>
