### ISSUE TITLE
TTESV deleted but still shown in README section "Datasets Available"

### ISSUE THREAD

**Issue by bbrewington** [tyndale/STEPBible-Data#25]
Most recent Commit where TTESV was deleted: 710542c1f249b91b44c2db1255fc7185fec040ce

Also, any background on why it was deleted?  Was that a mistake?

**Comment by DavidIB** [comment]
Thanks for this.
No, I don't know why it was deleted - an error I guess, though a most
disturbing one!
I'll restore it. But you might want to hold fire cos it is likely to be
greatly updated in the near future.

David IB

**Comment by bbrewington** [comment]
Oh, ok. Thanks for the info
