### ISSUE TITLE
TANTT - Sub-meaning: "§" symbol in Sub-meaning instead of "="

### ISSUE THREAD

**Issue by bbrewington** [tyndale/STEPBible-Data#26]
Example Ref: 42_Mrk.012.035 ...

There are two sub-meanings for David, one with an "=" sign and the other with "§":
* =David@Rut.4.17
* §David@Rut.4.17

File I'm referring to:
https://raw.githubusercontent.com/tyndale/STEPBible-Data/master/TANTT%20-%20Tyndale%20Amalgamated%20NT%20Tagged%20texts%20-%20TyndaleHouse.com%20STEPBible.org%20CC%20BY-NC.txt

Some other common sub-meanings with the § symbol
§Jesus@Mat.1.1
§Christ|Jesus@Mat.1.1
§1_God
§1_holy
§1_spirit
§Paul@Act.7.58           10

**Comment by DavidIB** [comment]
The form that's correct is:   §David@Rut.4.17
I can't find it in my source, so I must have corrected it, and it won't be
in any update.

David IB
