### ISSUE TITLE
Not fully compatible with OSHB

### ISSUE THREAD

**Issue by eliranwong** [tyndale/STEPBible-Data#3]
I downloaded OSHB yesterday.  And I found that TBESH do not have following entries, which are in OSHB:

H738, H2030, H2286a, H2286b, H3227, H3757, H3820, H5869, H6213, H6485, H6887, H7451, H7461, H8106, H8323

**Comment by DavidIB** [comment]
Dear Eliran

 

H3757 occurs only once, at Num.026.006-06

 

In the Hebrew lexicon you’ll see that:

H0738 is divided into a = אַרְיוֹךְ  and b = אַרְיֵה

H2030 is divided into a = הָרָה  and b = הָרִיָּה

Similarly for H8106

H3227 is divided into a = ‘on the right hand’ and b = the proper name ‘Yamin’

Similarly for H3920

H5869 is divided into a = ‘eye’ and b = ‘spring’ 

Similarly for H6213, H6887 (though this has 5 different meanings, a,b,c,d,e), H7451 (3 meanings), H8323

H6485 is divided into a for the verb and b for the noun

H7461 is divided into a = masc, and b = fem which have different meanings

 

We could, of course, divide Hebrew words into more sub-meanings (I I have indicated this with the sub-meaning tags) but the number tags aim to stay in line with the divisions in BDB. Most of that work was done by OpenScriptures. 

 

H2286 is a strange one. 

It used to be H2286a=חֲגָבָא & H2286b=חֲגָבָה  but these tags only occurred  at Neh.7.48 & Ezr.2.45 respectively which are identical individuals with identical names. For some reason they are given these different entries in BDB, and it looks like an error. 

BUT as a result of your email, I have reconsidered this and reversed the decision to remain in line with BDB, though I have tagged both occurrences as H2286b. Wycliffe 1395 has “Agaba” for both; Coverdale 1535 & Bishops 1568 have  "Hagaba" for both but KJV had “Hagabah” in Ezra and “Hagaba”, then everyone followed this error.  My guess this that this was part of the unthinking assumption by a translator that it must be a male name, so they removed the female final “h” to create a new name.

Most translations have followed that error – even the NIV, but at least I can get that fixed. Thanks for highlighting this. 

 

David IB
