### ISSUE TITLE
μέγιστα (2Pe 1:4)

### ISSUE THREAD

**Issue by Andley** [tyndale/STEPBible-Data#30]
δι᾽ ὧν τὰ τίμια καὶ μέγιστα ἡμῖν ἐπαγγέλματα δεδώρηται, 
where μέγιστα should be parsed as A-**A**PN-S instead of A-**N**PN-S.

**Comment by DavidIB** [comment]
Thanks – absolutely right! I’ve changed the data so it will be correct when updated.

David IB
