### ISSUE TITLE
morphhb or stepbible-data

### ISSUE THREAD

**Issue by john916zhang** [tyndale/STEPBible-Data#32]
Thanks for providing this wonderful resource. I am developing a quiz website for students of Biblical Hebrew. I see both this repository and 'morphhb' (https://github.com/openscriptures/morphhb) providing full Hebrew bible and parsing information. I am wondering which is better, accurate, and updated. Thanks again.

**Comment by DavidIB** [comment]
They both come from different sources: MorphHB was created by volunteer
scholars  organised by Open Scriptures.
The STEPBible data is based on the ETCBC data from Amsterdam Free
University. I've done some comparisons of this data with the MorphHB
and with the commercial Westminster data (which is used by Logos,
Accordance etc) and I have been VERY impressed by the quality.

*David IB*
