### ISSUE TITLE
TBESG - missing G4773

### ISSUE THREAD

**Issue by eliranwong** [tyndale/STEPBible-Data#4]
Dear David,

  There is no entry on G4773 in TBESG here.

  Instead, I find an entry without Strong's number, quoted below:

συγγενευς	kindred	συγγενής	G:A	<b>σνγγενής</b>, -ές (dative pl., -εῦσιν, <a href="javascript:void(0)" title="Mrk.6:4, Luk.2:44">Refs</a>, as though from -εύς, see Swete, <i>Mk.</i>, l.with; Bl., § 8, 6; cf. 1Ma.10:89 A א2 *;) <BR /> (&lt; σύν, γένος), [in LXX for דּוֹד, דּוֹדָה, מִשְׁפָּחָה ;] <BR /> __1. congenital, natural, innate. <BR /> __2. <b>akin to</b>; as subst., <b>a kinsman</b>: <a href="javascript:void(0)" title="Mrk.6:4, Luk.1:58 2:44 14:12 21:16, Jhn.18:26, Act.10:24">Refs</a>; of tribal kinship, <a href="javascript:void(0)" title="Rom.9:3 16:7, 11 16:21">Refs</a>.†<BR /> <re> <re><i>SYN.</i>: ἴδιος, οἰκεῖος (which see)</re></re>  (AS)

Blessings,
Eliran Wong

**Comment by DavidIB** [comment]
Thanks!

I’ve corrected the data so it will be fixed at next update

 

David IB
