### ISSUE TITLE
Missing newline in TVTMS

### ISSUE THREAD

**Issue by jonathanrobie** [tyndale/STEPBible-Data#41]
This is broken in [TVTMS](https://raw.githubusercontent.com/tyndale/STEPBible-Data/master/TVTMS%20-%20Tyndale%20Versification%20Traditions%20with%20Methodology%20for%20Standardisation%20for%20Eng%2BHeb%2BLat%2BGrk%2BOthers%20-%20STEPBible.org%20CC%20BY.txt).

Note the text all the way to the right on the last line.  It was probably intended to be a line all its own.  You may have to scroll way to the right to see it.

```tsv
$Num.20:28-29	English	Hebrew	Latin	Greek								
TEST: If...	Num.20:29=Last	Num.20:29=Last	Num.20:30=Last	Num.20:29=Last								
SubdividedVerse	Num.20:28	Num.20:28	Num.20:28-29	Num.20:28								
OneToOne	Num.20:29	Num.20:29	Num.20:30	Num.20:29						SubdividedVerse	Num.20:29	Num.20:29	Num.20:30	Num.20:29	
```

**Comment by DavidIB** [comment]
Thanks!
Fixed and uploaded.
*David IB*

**Comment by jonathanrobie** [comment]
Excellent!  The versification program is now unbroken again.
