### ISSUE TITLE
TBESG - Unexpected lines found

### ISSUE THREAD

**Issue by eliranwong** [tyndale/STEPBible-Data#6]
Dear David,

  In TBESG, lines are found where they don't start with Strong's numbers entries followed by a TAB.  They are listed below.  Thanks for your great resource.

Blessings,
Eliran

line 1969: @AS_Def=	
line 1970: @MLsjDefs=	
line 3512: $
line 3513: @STEPUnicodeAccented=	ἔξειμι
line 3514: @StrNo=	
line 3515: @StepGloss=	
line 3516: @STEPUnicodeAccented=	
line 3517: @STEPMorph=	
line 3518: @MounceMedDef=	
line 3519: @AS_Def=	
line 3520: @MLsjDefs=	
line 4636: @AS_Def=	
line 4637: @MLsjDefs=	
line 4873: @AS_Def=	
line 4874: @MLsjDefs=	
line 5245: $
line 5246: @STEPUnicodeAccented=	καταφάγω
line 5247: @StrNo=	
line 5248: @StepGloss=	
line 5249: @STEPUnicodeAccented=	
line 5250: @STEPMorph=	
line 5251: @MounceMedDef=	
line 5252: @AS_Def=	
line 5253: @MLsjDefs=	
line 8028: @AS_Def=	
line 8029: @MLsjDefs=	
line 8493: @AS_Def=	
line 8494: @MLsjDefs=	
line 8577: @AS_Def=	
line 8578: @MLsjDefs=	
line 9821: @AS_Def=	
line 9822: @MLsjDefs=	
line 10132: @STEPMorph=	G:N-N

**Comment by DavidIB** [comment]
Thank you so much!

I’ll try to fix it soon.

 

David IB

**Comment by DavidIB** [comment]
Corrections posted
