### ISSUE TITLE
TANTT - lines of different formats

### ISSUE THREAD

**Issue by eliranwong** [tyndale/STEPBible-Data#7]
Dear David,

  In your newly uploaded TANTT, I found the following lines, formats of which are different from the rest of the file.  You may simply locate them all by searching ^[0-9]+?_[^\n\t]*?\t\-

Line 6566: 41_Mat.012.004	-16a=INSTWH	ο	ὃ	G3739=R-ASN	ὅς, ἥ=which		-	-	-	RR ----ASN-
Line 6991: 41_Mat.012.029x	-XXz=Z		{<⸀>διαρπάσει SBL WH Treg RP NA TH: διαρπάσῃ NIV  <Notes re NIV+NA: NIV=NA does translate as indicative "can plunder" (unlike ESV)>				
Line 6993: 41_Mat.012.029x	-XX=x	διαρπαση	διαρπάσῃ	G1283=V-AAS-3S	διαρπάζω=to rob		-	-	-
Line 6994: 41_Mat.012.029x	-XXz=Z		}					
Line 9142: 41_Mat.014.034	-05a~=INSTWH	επι	ἐπὶ	G1909=PREP	ἐπί=upon/to/against		-	-	-	P- --------
Line 9660: 41_Mat.015.030	-14c~=IN	κυλλους	κυλλούς	G2948=A-APM	κυλλός=crippled		-	-	-
Line 9662: 41_Mat.015.030	-16a~=INW	κωφους	κωφούς	G2974=A-APM	κωφός=deaf/mute		-	-	-
Line 12341: 41_Mat.020.010	-19a~=INSTWH	το	τὸ	G3588=T-ASN	ὁ=the/this/who		-	-	-	RA ----ASN-
Line 50535: 43_Luk.023.012	-29a+=SW+INTH	αυτους	αὑτούς	G1438=F-2APM	ἑαυτοῦ=my/your/him-self		-	-	-
Line 53402: 44_Jhn.002.024	-10a+=SW+INT	αυτον	αὑτὸν	G1438=F-3ASM	ἑαυτοῦ=my/your/him-self		-	-	-
Line 63133: 44_Jhn.013.032	-17a+=SW+INTH	αυτω	αὑτῷ	G1438=F-3DSM	ἑαυτοῦ=my/your/him-self		-	-	-
Line 63371: 44_Jhn.014.007	-14a~=IN	γνωσεσθε	γνώσεσθε	G1097=V-FDI-2P	γινώσκω=to know		-	-	-
Line 67402: 44_Jhn.020.010	-06a+=SW+INT	αυτους	αὑτοὺς	G1438=F-3APM	ἑαυτοῦ=my/your/him-self		-	-	-
Line 70475: 45_Act.004.005	-21a~=INSTWH	εν	ἐν	G1722=PREP	ἐν=in/on/among		-	-	-	P- --------
Line 79361: 45_Act.016.012	-11a+=N	πρωτης	πρώτης	G4413=A-GSF-S	πρῶτος=first	§4_best/most_important	-	-	-
Line 81906: 45_Act.019.038	-10a+=mNH	εχουσι	ἔχουσι	G2192=V-PAI-3P	ἔχω=to have/be		-	-	-	V- 3PAI-P--
Line 84237: 45_Act.023.007	-05b~=INTH	ειποντος	εἰπόντος	G2036=V-2AAP-GSM	ἔπω, ἐρῶ, εἶπον=to say		-	-	-	V- -AAPGSM-
Line 113760: 51_Php.003.021	-29a+=SW+INTH	αυτω	αὑτῷ	G1438=F-3DSM	ἑαυτοῦ=my/your/him-self		-	-	-
Line 128515: 60_Jas.003.003	-02b~=INSTW+H	ει	εἰ	G1487=CONJ	εἰ=if	§1_if/whether	-	-	-
Line 130667: 61_1Pe.003.021	-04a~=INSTWH	υμας	ὑμᾶς	G4771=P-2AP	σύ=you		-	-	-	RP ----AP--
Line 138946: 67_Rev.008.006	-12a+=SW+INTH	αυτους	αὑτοὺς	G1438=F-3APM	ἑαυτοῦ=my/your/him-self		-	-	-

**Comment by DavidIB** [comment]
THanks - should be gone in new update
