### ISSUE TITLE
many words are missing in TANTT

### ISSUE THREAD

**Issue by eliranwong** [tyndale/STEPBible-Data#9]
I think there may probably be some serious errors in current file of TANTT, uploaded in this repo.
TANTT has more than 100 words less than NA27

there are at least some missing words at the beginning of some verses. e.g. 41_Mat.020.005,
all words are missing in some verses, e.g. 67_Rev.012.018

**Comment by eliranwong** [comment]
Dear David,

Regarding the issue mentioned above, here are some of the verses you may want to check.  There may also be some missing words in other verses.

41_Mat.017.015
41_Mat.020.005
42_Mrk.003.020
42_Mrk.016.009
43_Luk.002.002
43_Luk.006.018
43_Luk.007.029
44_Jhn.001.015
45_Act.002.011
45_Act.004.006
45_Act.024.019
46_Rom.007.010
46_Rom.009.012
47_1Co.014.032
48_2Co.001.007
48_2Co.008.014
48_2Co.009.009
48_2Co.013.013
50_Eph.005.014
53_1Th.002.007
53_1Th.002.012
55_1Ti.003.005
59_Heb.003.010
59_Heb.008.005
61_1Pe.002.015
67_Rev.002.028
67_Rev.012.018

**Comment by DavidIB** [comment]
There was an error in the export code. Thanks for pointing  out there was a prob.

**Comment by DavidIB** [comment]
Thanks - Now fixed.
